scrape_configs:
  - job_name: 'docker_stats_exporter'
    metrics_path: /
    scrape_interval: 5s
    static_configs:
    - targets:
        - 'docker_stats_exporter:9487'

# Uncomment it if you want to enable cAdvisor to scrape othe metrics
# constainer cAdvisor
# - job_name: cadvisor
#   scrape_interval: 5s
#   static_configs:
#     - targets:
#       - cadvisor:8080
